// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nikktercsviqrnluseol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5pa2t0ZXJjc3ZpcXJubHVzZW9sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMDk0MTEsImV4cCI6MjA1OTg4NTQxMX0.isUlLLemFuaw9UioF48zp-4RO2N2FvVY7D0dl-ZS8mM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);